---
- hosts: lb
  become: yes
  
  vars:
    dir_name: loadbalancer

  tasks:
    - name: System update
      ansible.builtin.apt:
        update_cache: yes
       
    - name: Install packages
      ansible.builtin.apt:
        name:
          - nginx
        state: present
        
    - name: Create nginx site config
      ansible.builtin.template:
        src: templates/nginx-{{ dir_name }}.j2
        dest: "/etc/nginx/sites-available/{{ dir_name }}"
      notify: restart nginx

    - name: Enable nginx site
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ dir_name }}"
        dest: "/etc/nginx/sites-enabled/{{ dir_name }}"
        state: link
      notify: restart nginx

    - name: Remove default nginx config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Allow nginx in ufw
      community.general.ufw:
        rule: allow
        name: '{{ item }}'
      loop:
        - OpenSSH
        - Nginx Full

  handlers:
  
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted