- name: Set up PostgreSQL VM
  hosts: postgresql
  vars:
    vm_name: postgresql
  remote_user: nda
  become: true
  tasks:
    - name: Ensure PostgreSQL is installed
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Ensure NGINX is installed
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Lynis is installed
      ansible.builtin.apt:
        name: lynis
        state: present

    - name: Ensure /var/log/lynis directory exists
      ansible.builtin.file:
        path: /var/log/lynis
        state: directory
        mode: '0644'
        owner: root
        group: root

    - name: Lynis cronjob script from a template
      ansible.builtin.template:
        src: templates/lynis-cronjob.j2
        dest: /usr/local/bin/lynis-cronjob.sh
        mode: '0755'
        owner: root
        group: root

    - name: Ensure cronjob is set up
      ansible.builtin.cron:
        name: "lynis cronjob"
        minute: "0,30"
        user: root
        job: "/usr/local/bin/lynis-cronjob.sh"
